const SOURCES_LOADED = 'SOURCES_LOADED';
const FILTER_NEWS = 'FILTER_NEWS';
const FIRST_NEWS_PAGE_LOADED = 'FIRST_NEWS_PAGE_LOADED';
const NEXT_NEWS_PAGE_LOADED = 'NEXT_NEWS_PAGE_LOADED';

export const actionConstants = {
  SOURCES_LOADED,
  FILTER_NEWS,
  FIRST_NEWS_PAGE_LOADED,
  NEXT_NEWS_PAGE_LOADED,
};
